Repository checkmarx-ltd/CLI, pull requests merged in 2021-11, with the labels that each got.

#82 SCA scan timeout
  src/main/java/com/cx/plugin/cli/constants/ArgDescriptions.java
  src/main/java/com/cx/plugin/cli/constants/Command.java
  src/main/java/com/cx/plugin/cli/constants/Parameters.java
  src/main/java/com/cx/plugin/cli/utils/CxConfigHelper.java
Labels: size/XS

#84 Completed the Scan level custom field implementation for CLI
  src/main/java/com/cx/plugin/cli/constants/ArgDescriptions.java
  src/main/java/com/cx/plugin/cli/constants/Command.java
  src/main/java/com/cx/plugin/cli/constants/Parameters.java
  src/main/java/com/cx/plugin/cli/utils/CxConfigHelper.java
Labels: size/S

#85 Cli sca resolver
  src/main/java/com/cx/plugin/cli/constants/ArgDescriptions.java
  src/main/java/com/cx/plugin/cli/constants/Command.java
  src/main/java/com/cx/plugin/cli/constants/Parameters.java
  src/main/java/com/cx/plugin/cli/utils/CxConfigHelper.java
Labels: size/M
